### ISSUE TITLE
Fatal error: can't create obj/clevo-indicator.o: No such file or directory

### ISSUE THREAD

**Issue by simontong** [AqD/clevo-indicator#1]
Thanks for creating this tool, I've been looking everywhere for my Clevo W55xEU to control fan speed.

When trying to run 'make install' it gave me the following error:
Fatal error: can't create obj/clevo-indicator.o: No such file or directory

All I had to do to fix was to create the 'obj' folder and then run again and it worked.

**Comment by AqD** [comment]
Thank you! Fixed in commit 575ba321ef7ab9a594b592ed48118a54c1083040

**Comment by KellyRDC** [comment]
Hi, have you ever experience when running the clevo-indicator, it says "multipe runnning insatnce on clevo-indicator" Im not able to see the output.

**Comment by AqD** [comment]
It's to prevent you from running it multiple times. Kill the other one first... Is it missing on the notification area?
